### ISSUE TITLE
How do I use this gem?

### ISSUE THREAD

**Issue by luizkowalski** [crimsonknave/trakt#1]
Hey, I've been trying to understand Trakt API when I crossed paths with your gem, that seems to be more up to date than other Trakt gems, but how do I use it? Can you provide a simple snippet or something? I want to list all popular and trending movies :)

**Comment by crimsonknave** [comment]
So, I haven't published the gem to rubygems yet. I was hoping to polish it up some more before I did so, and write some tests. I believe that right now this works pretty well for any of the read only stuff, I haven't done as much testing of writing.

I can try to whip up a readme, but in the mean time if you look at the test.rb file in the root there are some examples.  Additionally, you'll need to create an api key by going to settings -> Your API Apps and then creating a new app (you'll fill in the redirect uri with the value they specify for pin auth). Then export your app's client id as TRAKT_CLIENT_ID (https://github.com/crimsonknave/trakt/blob/bb26766aaac877c07b59dcf4da4f5fd2c77903d9/lib/trakt/client.rb#L9).
